server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/socialnetwork
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none